{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d7b3d6d8",
   "metadata": {},
   "source": [
    "# Validation of a YOLOv5 model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b18a3922",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "# Root directory\n",
    "root_dir = '/Users/Holmes/Research/Projects/vespai'\n",
    "sys.path.insert(0, root_dir)\n",
    "os.chdir(os.path.join(root_dir, 'models/yolov5'))  # Move to yolov5\n",
    "\n",
    "# Automatically reload imported programmes\n",
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5939ae0d",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%capture readout\n",
    "# Data and project\n",
    "data_dir = os.path.join(root_dir, 'datasets/polygons-21')\n",
    "proj_name = 'new-weights-on-21-data'\n",
    "\n",
    "# Locate local config file\n",
    "yaml_path = os.path.join(data_dir, 'config-local.yaml')\n",
    "\n",
    "# To compute mAP on test data (x1)\n",
    "#   opt `--half` for FP16 inference\n",
    "#   opt `--augment` for augmented inference\n",
    "!python val.py  --weights ../yolov5-params/yolov5s-21-ip.pt \\\n",
    "                --project ../yolov5-runs/val \\\n",
    "                --name {proj_name} \\\n",
    "                --task test \\\n",
    "                --data {yaml_path} \\\n",
    "                --save-txt \\\n",
    "                --save-hybrid \\\n",
    "                --save-conf \\\n",
    "                --verbose"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "23e945d3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mval: \u001b[0mdata=/Users/Holmes/Research/Projects/vespai/datasets/polygons-21/config-local.yaml, weights=['../yolov5-params/yolov5s-21-ip.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=test, device=, workers=8, single_cls=False, augment=False, verbose=True, save_txt=True, save_hybrid=True, save_conf=True, save_json=False, project=../yolov5-runs/val, name=new-weights-on-21-data, exist_ok=False, half=False, dnn=False\r\n",
      "YOLOv5 ðŸš€ 2022-7-19 Python-3.9.13 torch-1.11.0 CPU\r\n",
      "\r\n",
      "Fusing layers... \r\n",
      "YOLOv5s summary: 213 layers, 7015519 parameters, 0 gradients\r\n",
      "\r",
      "\u001b[34m\u001b[1mtest: \u001b[0mScanning '/Users/Holmes/Research/Projects/vespai/datasets/polygons-21/labe\u001b[0m\r",
      "\u001b[34m\u001b[1mtest: \u001b[0mScanning '/Users/Holmes/Research/Projects/vespai/datasets/polygons-21/labe\u001b[0m\r\n",
      "\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\r\n",
      "                 all        215        225          1          1      0.995      0.995\r\n",
      "        Vespa crabro        215        104          1          1      0.995      0.995\r\n",
      "      Vespa velutina        215        121          1          1      0.995      0.995\r\n",
      "Speed: 1.8ms pre-process, 209.8ms inference, 0.4ms NMS per image at shape (32, 3, 640, 640)\r\n",
      "Results saved to \u001b[1m../yolov5-runs/val/new-weights-on-21-data\u001b[0m\r\n",
      "187 labels saved to ../yolov5-runs/val/new-weights-on-21-data/labels\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10390fb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10390fb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10390fb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10390fb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10390fb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10390fb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10af1eb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10af1eb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10c1a3b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10af1eb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10af1eb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10c1a3b80>\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10af1eb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespa  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10af1eb80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "i/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10c1a3b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10c1a3b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10c1a3b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10c1a3b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10fec7b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10fec7b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10fec7b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10fec7b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10fec7b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10fec7b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10914db80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10914db80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10914db80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10914db80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10914db80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10914db80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10a776b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10a776b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10a776b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10a776b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10a776b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x10a776b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x111822b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x111822b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x111822b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x111822b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x104960b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x104960b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x104960b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x104960b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x104960b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x104960b80>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x110d94550>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/opt/miniconda3/envs/vespai/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Save readout\n",
    "print(readout.stdout)\n",
    "with open('../yolov5-runs/val/' + proj_name + '/readout.txt', 'w') as f:\n",
    "    f.write('\\n'.join(readout.stdout.split(\"\\n\")))\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
